# Trabalho final de estatística para Ciência de Dados

## Enunciado

Objetivos: Aplicar os conhecimentos em estatística.
Dada uma matriz n x n esférica:
Esférica: o indivíduo, digamos na borda direita pode ainda se deslocar para a direita,
surgindo na borda esquerda da matriz. O mesmo acontece para as outras bordas;
1. Alimentá-la inicialmente com os seguintes indivíduos:

  1.1. Um infectado, cuja posição é aleatória;
  
  1.2. Um número randômico de assintomáticos, cujas posições são aleatórias;
  
  1.3. Um número randômico de sintomáticos, cujas posições são aleatórias;

2. A forma de desenvolvimento:
  
  2.1. A rede evolui em passos, cada passo significa a mudança de todos os indivíduos
  infectados de posição. Antes disso, ele realiza todas as tarefas de infecção sobre os
  outros indivíduos;
3. A mobilidade;

  3.1. Somente os indivíduos infectados caminham ou mudam de posição no passo. Os
outros indivíduos permanecem estáticos;

  3.2. Apenas indivíduos infectados circulam na rede
4. O indivíduo infectado deverá infectar os seus vizinhos diretos (não diagonais) em dois
casos, desenvolvidos separadamente:

  4.1. Apenas com 30% de chance;

  4.2. Com 100% de chance;
5. A infecção:

  5.1. O infectado adquiri a propriedade de infectar;
  
  5.2. O infectante infecta os seus vizinhos, considerando as regras do item 4;
    
    5.2.1. O indivíduo assintomático apresenta uma infecção do tipo 1;
    
    5.2.2. Os indivíduos sintomáticos apresentam uma infecção tipo 2:
    
    5.2.3. O programa deve escolher quem é sintomático com chance de 20%.
6. A cura:

  6.1. A cura dos infectados ocorre após 10 atualizações;
7. A morte:

  7.1. A morte pode ocorrer para os indivíduos do tipo 2, do início da infecção até a 10 atualização com 2% de chance;
8. Para cada um dos casos do item 4, verifique com quantos passos sua rede atinge 100%
de infectados e com 50% deste valor colha os seguintes dados:

  8.1. Número de assintomáticos;
  
  8.2. Número de sintomáticos;
  
  8.3. Número de curados;
  
  8.4. Número de mortos;
9. Os valores gerados no item 8, para cada caso do item 4, devem analisados
estatisticamente e:

  9.1. Realize a estatística descritiva;

  9.2. Verificar se o experimento se ajusta a uma distribuição normal.

  9.3. Verifique com quantos passos sua rede atinge 100% de infectados:

    9.3.1. Com base nestes dados, verifique com 95% de confiança, qual o número de cada indivíduo no passo n/2+1;
    
    9.3.2. Verifique a independência das contaminações entre assintomáticos e
    sintomáticos através de CHI-Square, com base na seguinte relação: são
    esperados 18% de doentes e 80% de assintomáticos e 2% de mortos;

In [8]:
# %cd /content
!git clone https://github.com/eduardodut/Trabalho_final_estatistica_cd.git

# %matplotlib inline

Cloning into 'Trabalho_final_estatistica_cd'...
remote: Enumerating objects: 256, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 256 (delta 221), reused 235 (delta 200), pack-reused 0
Receiving objects: 100% (256/256), 42.09 KiB | 3.01 MiB/s, done.
Resolving deltas: 100% (221/221), done.


In [9]:
%cd Trabalho_final_estatistica_cd/src
from Simulador import Simulador

/content/Trabalho_final_estatistica_cd/src/Trabalho_final_estatistica_cd/src/Trabalho_final_estatistica_cd/src


In [13]:
chance_infeccao = 0.3             
chance_infeccao_tipo2 = 0.2       
chance_morte = 0.2                
atualizacoes_cura = 10           
percentual_inicial_tipo1 = 0.05    
percentual_inicial_tipo2 = 0.01


sim = Simulador(
    10,
    percentual_inicial_tipo1, 
    percentual_inicial_tipo2, 
    chance_infeccao,
    chance_infeccao_tipo2,
    chance_morte,atualizacoes_cura)

# dict = {'num_sadios':1,
#                 'num_infect_t1':2,
#                 'num_infect_t2':3,
#                 'num_curados':4,
#                 'num_mortos':5}
# s = pd.Series(dict)                
# sim.dataframe = sim.dataframe.append(s, ignore_index=True)

print(sim.matriz_individuos)
print(sim.matriz_individuos.flatten().reshape(10,10))
#print(sim.num_inicial_tipo2)

# cmap = ListedColormap(['w', 'y', 'r', 'b', 'black'])
# plt.matshow(sim.matriz_individuos, cmap = cmap);plt.show();




[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
import numpy as np

matriz_individuos = np.zeros([10,10])
print(matriz_individuos.flatten().reshape(10,10))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Simulações

In [ ]:














#@title Gerar simulações
#@markdown ### Selecione os parâmetros das simulações
#@markdown ### O resultados podem ser acessados no dataframe "simulacoes"



numero_simulacoes = 2156 #@param {type:"slider", min:1, max:5000, step:1}
tamanho_matriz = 2056 #@param {type:"slider", min:10, max:10000, step:1}
chance_infeccao = 30 #@param {type:"slider", min:0, max:100, step:1}
chance_morte = 2 #@param {type:"slider", min:0, max:100, step:1}
chance_assintomatico = 20 #@param {type:"slider", min:0, max:100, step:1}


*   população total da simulação
*   num_inicial de sintomáticos
*   num_inicial de assintomáticos
*   percentual de chance de infecção

*   numero de passos até 100% infectados
    *   numero_mortos, 
    *   numero de doentes de cada tipo  
    *   número de curados
*   numero de passos até 50% infectados
    *   numero_mortos, 
    *   numero de doentes de cada tipo  
    *   número de curados
*   numero de passos até extinção da doença da matriz
    *   numero_mortos, 
    *   numero de doentes de cada tipo  
    *   número de curados




## Testes estatísticos


## Conclusões

In [ ]:
# teste